### ISSUE TITLE
oops zipkin proto support missing :)

### ISSUE THREAD

**Issue by adriancole** [HotelsDotCom/pitchfork#9]
`POST /api/v2/spans` endpoint if content type is `application/x-protobuf` use SpanBytesDecoder.PROTO3

https://github.com/openzipkin/zipkin-api/blob/master/zipkin.proto

**Comment by worldtiki** [comment]
Yes it is, thanks for the heads up :)

Draft here: https://github.com/HotelsDotCom/pitchfork/pull/10

I didn't have time to do any sort of testing. I'll work on it later this week.

**Comment by worldtiki** [comment]
Implemented in #10
